name: Lint source code
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
      - name: build
        run: source $HOME/.local/share/xs-dev-export.sh && npm run build
        working-directory: ./firmware
      - name: lint
        run: npm run lint
        working-directory: ./firmware